/*******************************************************************************
 *  Copyright 2019 Centre for Development of Advanced Computing(C-DAC), Pune
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *  
 *   http:\www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.07 at 11:47:30 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:hl7-org:v3", 
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
)
/*@javax.xml.bind.annotation.XmlSchema(
    elementFormDefault=javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
    namespace="urn:hl7-org:v3",
    xmlns={@javax.xml.bind.annotation.XmlNs(prefix="voc",
                  namespaceURI="urn:hl7-org:v3/voc")}
)*/

package cdac.medinfo.model;
